### ISSUE TITLE
Example Jest tests fail to compile bugsnag-react-native library

### ISSUE THREAD

**Issue by wordofchristian** [bugsnag/bugsnag-react-native#10]
The newest release of react native includes some built in jest tests. https://github.com/facebook/react-native/releases/tag/v0.35.0

If you try to run them after adding the bugsnag react native library you get a compilation failure.

![screenshot 2016-10-12 18 07 17](https://cloud.githubusercontent.com/assets/555044/19333044/bdc13d60-90a6-11e6-8794-293238e75d5a.png)

I think the jest [react native preset](https://github.com/facebook/jest/blob/master/packages/jest-react-native/jest-preset.json#L19) is set to skip preprocessing files inside the node_modules folder. 

I tried adding the following to a sample project's package.json to see if it would help:

``` json
  "jest": {
    "preset": "jest-react-native",
    "preprocessorIgnorePatterns": [
      "node_modules/(?!(jest-)?react-native|react-clone-referenced-element|bugsnag-react-native)"
    ]
  },
```

This produced the error

```
    Bugsnag: No native client found. Is BugsnagReactNative installed in your native code project?

      at new Client (node_modules/bugsnag-react-native/lib/Bugsnag.js:27:7)
      at Object.<anonymous> (bugsnag.js:7:12)
      at Object.<anonymous> (index.ios.js:15:14)
      at Object.<anonymous> (__tests__/index.ios.js:3:15)
```

**Comment by kattrali** [comment]
I think it makes the most sense to mock the bugsnag client entirely from tests (`jest.mock("bugsnag-react-native"`). That would fix the latter error. 

For the former, I needed to set [`transformIgnorePatterns`](http://facebook.github.io/jest/docs/tutorial-react-native.html#transformignorepatterns-customization) instead of `preprocessorIgnorePatterns`.

We could add an example demonstrating this for future reference.
