### ISSUE TITLE
The metadata recorded for key 'app' is not formatted as key/value pairs. Discarding

### ISSUE THREAD

**Issue by patlux** [bugsnag/bugsnag-react-native#132]
Hello,

in the ios logs I get the message 

> The metadata recorded for key 'app' is not formatted as key/value pairs. Discarding

My test error:

```javascript  
BugsnagClient.notify(new Error('ios test'), report => {
  console.log('report', report);
  return report;
});
```
The report looks like this:

<img width="449" alt="screen shot 2017-08-17 at 12 07 42" src="https://user-images.githubusercontent.com/4481570/29407565-126d37ec-8345-11e7-88db-62ef5b5160f2.png">

What's wrong?

**Comment by kattrali** [comment]
The data looks fine; which versions of react native and bugsnag-react-native are you using, @patlux?

**Comment by patlux** [comment]
react-native v0.45.1
bugsnag-react-native v2.3.1
@kattrali

**Comment by kattrali** [comment]
Upon investigation, any nested object is now being serialised as a string instead of as JSON when crossing the native bridge. I'm investigating solutions where we do the serialisation/deserialisation within the library to fix this. So something like:

JS side of `notify`: metadata stringified using `JSON.stringify`
Native side of `notify`: converts metadata to `Map`/`NSDictionary` via `JSONObject`/`NSJSONSerialization`

cc @sudoplz

**Comment by SudoPlz** [comment]
Let us know if we have to do something on our end @kattrali !

Thanks

**Comment by kattrali** [comment]
Fixed in 2.3.2! Thanks for the debugging detail, @patlux @SudoPlz. 🎉

**Comment by SudoPlz** [comment]
Please publish this @kattrali the npm version is still 2.3.1

**Comment by kattrali** [comment]
So odd 🤔 I republished and everything seems to be ok. @SudoPlz can you retry?

**Comment by SudoPlz** [comment]
It's there now. Thanks!
💥
