### ISSUE TITLE
[Feature Request] Support for Expo non-ejected apps

### ISSUE THREAD

**Issue by Jujunol** [bugsnag/bugsnag-react-native#137]
### Expected behavior
It'd be great if we could setup and use Bugsnag on React Native apps that aren't ejected

### Observed behavior
However, upon using Bugsnag Native just using `npm i --save bugsnag-react-native` then importing and creating a client causes the following error:

_"Bugsnag: No native client found. Is BugsnagReactNative installed in your native code project"_

After reading, it looks like this is an issue caused because, in expo non ejected apps, there isn't any `AndroidManifest.xml`, `MainApplication.java` or `Info.plist`.

### Version
```
    "expo": "^19.0.0",
    "react-native": "^0.46.1",
    "bugsnag-react-native": "^2.3.2",
```

#### Can't comment on Issues?
Some users have been unable to comment on Github issues when an [adblocker extension is enabled](https://docs.bugsnag.com/platforms/browsers/faq/#is-bugsnag-blocked-by-ad-blockers).
We recommend temporarily disabling the extension, or if that fails, contacting support@bugsnag.com.

**Comment by kattrali** [comment]
Thanks for the report, @Jujunol! That's a good idea. We could experiment with some example apps to see what configuration needs to change for Expo.

**Comment by yordis** [comment]
@kattrali any updates on this one? We are trying to convert the project to Expo and we are currently using Bugsnag and we dont want to trade off anything 😄

**Comment by myorukoglu** [comment]
Any movement on this one?  This is a deal breaker for us and Bugsnag.  We've been happy so far using Bugsnag with our React Native apps but as we move to Expo we will have to look for another error reporting tool.

**Comment by kattrali** [comment]
@myorukoglu @yordis Working on it, but thus far its required some deeper changes than expected. I'm having a bit of trouble getting a simple non-ejected Expo app set up as an example.

**Comment by yordis** [comment]
You couldn't care about any IOS/Android code, just the Javascript piece which  I am guessing you know that already 😄 I hope it doesn't take that long to get it done (hopefully before I finish converting the project). Cheers

**Comment by kattrali** [comment]
@yordis let's hope! 🤞

**Comment by appjitsu** [comment]
+1

**Comment by philolo1** [comment]
+1

**Comment by AlexViapiano** [comment]
+1

**Comment by Shaita-KrZ** [comment]
+1

**Comment by lc3t35** [comment]
+1

**Comment by yordis** [comment]
@kattrali any updates on this one?

**Comment by ryanspiffy** [comment]
+1

**Comment by hjohns** [comment]
+1

**Comment by netyweb** [comment]
+1

**Comment by calvincestari** [comment]
+1

**Comment by raulghm** [comment]
+1

**Comment by MattPark** [comment]
+1

**Comment by mkhuda** [comment]
+1

**Comment by pckz** [comment]
thanks! @kattrali  when you think this feature will be ready? 🙏

**Comment by philolo1** [comment]
@kattrali any update?

**Comment by hawkrives** [comment]
I think this request is solved by the [new setup process](https://github.com/bugsnag/bugsnag-react-native/blob/master/CHANGELOG.md#2101-2018-07-20) described in the v2.10.1 `CHANGELOG`:

> This release simplies the installation and quick setup process to do all configuration in JavaScript, provided that React Native is the primary way to interact with your app (rather than having React Native components as a part of a larger native app). See the integration guide's [updated configuration instructions](
https://docs.bugsnag.com/platforms/react-native/#basic-configuration).

**Comment by fractalwrench** [comment]
@hawkrives you still need to setup native Android/Cocoa e.g. by calling `[BugsnagReactNative start]` within your AppDelegate, when using v2.10.1. The new setup process just changes our recommendations for configuring Bugsnag to use non-default options, such as setting the `releaseStage` for example. I will update our documentation to make this a bit clearer.

I can confirm that Expo support is still in the works.

**Comment by sweinertjr** [comment]
+1

**Comment by SpaceTrev** [comment]
+1

**Comment by jlubeck** [comment]
Any updates on this @kattrali  ? Looked like it was so close back in April but nothing since...Thanks!

**Comment by joelcogen** [comment]
Any update on this, or at least a workaround? Thanks!

**Comment by kattrali** [comment]
Progress: When done, expo support will live with the other JS integrations, here in [bugsnag-js](https://github.com/bugsnag/bugsnag-js/tree/universal). I've ported the previous integration to be based from that branch, though its not shipped yet. Its usable and reports uncaught exceptions, etc. Though it still needs documentation particularly around integrating with react error boundaries, etc. That's why it is using the shared JS interface rather than the existing bugsnag-react-native base.

For the curious, current expo progress lives in a branch [here](https://github.com/bugsnag/bugsnag-js/tree/kattrali/expo), if you want to try it and/or leave some feedback. Check out the [example app configuration](https://github.com/bugsnag/bugsnag-js/blob/b8a1b1480c808b74dc20b40f5d562a6c1218bcfb/packages/expo/examples/taskmaster/App.js#L1).

**Comment by haikyuu** [comment]
@kattrali i suggest you get in touch with the Expo team for this. They [helped](https://github.com/expo/sentry-expo) the sentry team already, and there is no reason they wouldn't do the same with Bugsnag.

**Comment by kellypacker** [comment]
Can anyone give a specific example of how to install the expo package on the expo branch? Seems like it would be:

```
yarn add @bugsnag/expo#expo
```

But that doesn't work. I've tried every iteration I could think of. Any help is appreciated.

**Comment by bengourley** [comment]
HI everyone. As @kellypacker has noticed, we are working on our Expo notifier now. It's not in an installable or usable state just yet. We'll let you know when we have an alpha release ready if anybody is keen to help test that before the full release.

**Comment by bengourley** [comment]
Hey again – we've now shipped our Expo notifier. Check out the docs [here](https://docs.bugsnag.com/platforms/react-native/expo/).

__tl;dr__ the best way to get set-up is to use our CLI:

```sh
npx bugsnag-expo-cli init
```

This will install the notifier, add configuration in `app.json` so that source maps are uploaded for publishes, and initialise bugsnag in your `App.js`. If you'd rather do things manually [that's cool too](https://docs.bugsnag.com/platforms/react-native/expo/manual-setup/).

After that take a look at how to set up an [error boundary](https://docs.bugsnag.com/platforms/react-native/expo/#capturing-react-render-errors).

Enjoy!
