### ISSUE TITLE
How do I access instantiated library in other classes?

### ISSUE THREAD

**Issue by asciiman** [bugsnag/bugsnag-react-native#24]
I would like to add breadcrumbs on each screen of my app.  Right now the only way it seems like I can do this is to construct the bugsnag library in my root index and then pass down the property to each screen in my app.  This is quite tedious.

It would be better to construct/configure the app in the root screen and then make bugsnag a singleton so I can access an instance in the rest of the app.

There must be some better way of accessing the configured library than passing the property throughout the entire app.

**Comment by wordofchristian** [comment]
One way you could do this is create a singleton module. Create a file that configures the bugsnag client and exports it. Then you can import this module in both your android and ios code. ES6 modules only get evaluated when they are first imported so anything that they export is effectively a singleton.

```javascript
// src/bugsnag.js
import { Client } from 'bugsnag-react-native';
const client = new Client('my-api-key');
export default client;
```

Then in another file:

```javascript
//somewhere else in the app
import bugsnag from './bugsnag';
bugsnag.leaveBreadcrumb('load main view', {type: 'navigation'});
```


If the relative paths get to be a pain (i.e. the `import bugsnag from '../../bugsnag';`) you [can use this nice solution to deal with it](https://github.com/facebook/react-native/issues/3099#issuecomment-221815006)

**Comment by JonasWho** [comment]
@wordofchristian I'm doing exactly this and I get the attached error. I'm pretty sure it does not relate to loading bugsnag from the singleton, but thought I would post it here anyway, since its the closest I get to a similar case. 
The error comes from line 53 in lib/Bugsnag.js (v.1.3.1)
Am I doing something wrong? 
<img width="471" alt="genymotion_-_google_galaxy_nexus_-_4_3_-_api_18_-_720x1280__720x1280__320dpi__-_192_168_56_101" src="https://cloud.githubusercontent.com/assets/925342/20833358/9a67e272-b88f-11e6-968c-1607ecac5fb0.png">
