### ISSUE TITLE
in the examples readme, show how to upload native symbols and js sourcemaps

### ISSUE THREAD

**Issue by pvinis** [bugsnag/bugsnag-react-native#282]
it would be very useful to have these two in the readme.
now if i run the example plain, and i make it crash, i get crash reports, but both js and native ones are unsymbolicated.

**Comment by johnkiely1** [comment]
Hi @pvinis,

As time has moved on somewhat since the original request, the [example application](https://github.com/bugsnag/bugsnag-react-native/tree/master/examples/plain) in this repository does have that information.

As of v7.3 the library itself has now become part of the [bugsnag-js](https://github.com/bugsnag/bugsnag-js) repository with a new example application added. The readme for this new example is in the process of being updated to reference the relevant documentation and will be updated shortly. 

If and when you decide to upgrade to the latest version of Bugsnag the upgrade guide can be found [here](https://github.com/bugsnag/bugsnag-js/blob/next/packages/react-native/UPGRADING.md) with full documentation available [here](https://docs.bugsnag.com/platforms/react-native/react-native/).
