### ISSUE TITLE
SetUser before first autocaptured session

### ISSUE THREAD

**Issue by gregersn** [bugsnag/bugsnag-react-native#289]
### Description
I am trying to set user data for automatically captured sessions, but to accomplish this there seems to be some missing native functions.

The best thing would be to be able to do a setUser as part of the configuration, but setUser seems to only be available after the client is configured and set up, and has done the first autocaptured session.

**Describe alternatives you've considered**
I tried doing something like the following:
```
config = new Configuration(apikey);
config.autoCaptureSessions = false;
const bugsnag = new Client(config);
bugsnag.setUser("someid", "", "");
bugsnag.config.autoCaptureSessions = true
bugsnag.startSession()
```

But that does not seem to reenable autoCaptureSessions.

I have tried looking through the source for underlaying modules as well, but it seems like to be able to accomplish this, some more of the native functions needs to be exposed up into the react-native-javascript-layer. 

I might be going at this the totally wrong way, and if I am, maybe the documentation is lacking some information?

**Comment by bengourley** [comment]
Hi @gregersn, thanks for bringing this up.

Whilst the `user` property is present in the session payload schema, it's not actually used by at all by the system. It's there to support the case when we do use it in the future, but for now it's actually discarded so it doesn't matter that nothing gets sent.

In terms of the implementation of this libarary (`bugsnag-react-native`), we'll be focusing some attention improving it in the near future.

**Comment by johnkiely1** [comment]
Hi @gregersn,

I appreciate this has been open for some time, it would be interesting to know your use case and you are trying to achieve by setting user data on the session directly?

Thanks

**Comment by gregersn** [comment]
We use the library with our own back-end, and need some way to differentiate between users when reporting sessions. 
If I remember correctly, the session always came in without any good way of setting a "user" for it, and it was not easily possible to differentiate if two sessions came from two different users or not. 

Sadly I can't, from the top of my head remember exactly the case, etc.

**Comment by johnkiely1** [comment]
Hi gregersn,

It sounds like the problem you are encountering is that the first session is being reported from the native layer but the configuration is being set on the JS layer and has not yet applied the user info at the point the session was sent. The way to solve this is to set the user on the native layer(s) configuration so that it can be in place earlier in the process. 

Assuming this is still an ongoing problem for you, I think this can be most easily resolved using the [new version](https://github.com/bugsnag/bugsnag-js/releases/tag/v7.3.3) of this library as there has been a shift to more native based configuration for reasons exactly like this. There is documentation [here](https://docs.bugsnag.com/platforms/react-native/react-native/configuration-options/#setuser) about how to set the user for each of the native layers. The latest release of the Bugsnag react-native library has been moved to be incorporated into bugsnag-js repo so would take a little bit of work to upgrade to. The guide for that is [here](https://github.com/bugsnag/bugsnag-js/blob/next/packages/react-native/UPGRADING.md).
