### ISSUE TITLE
SourceMap upload returns "Nothing to Upload" response

### ISSUE THREAD

**Issue by EIrwin** [bugsnag/bugsnag-react-native#31]
When I run the following command

```
curl https://upload.bugsnag.com/ \
  -F apiKey={My-API-key} \
  -F appVersion=1.0 \
  -F minifiedUrl="main.jsbundle" \
  -F minifiedFile=main.jsbundle \
  -F sourceMap=sourcemap.js \
  -F overwrite=true \
  -F /workspace/app/index.ios.js=app/index.ios.js
```

I get a response that says `Nothing to upload`

I am not sure what the last line of the command should be pointing at, but I feel like that is the incorrect part.

**Comment by bullmo** [comment]
@EIrwin, that response is being returned because the upload needs the source map file to be provided whereas the command you've given is just specifying the path to the file. For curl you'll need to prefix the path with @ to upload the file.

The last line that you've specified is used to upload any source files (so that the code context can be seen in Bugsnag). The key should be the path to the file (as referenced from the source map) and the value should be the file itself.

Full details can be found at https://docs.bugsnag.com/platforms/react-native/showing-full-stacktraces/.

In your example the curl command should be:

curl https://upload.bugsnag.com/ \
  -F apiKey={My-API-key} \
  -F appVersion=1.0 \
  -F minifiedUrl="main.jsbundle" \
  -F minifiedFile=@main.jsbundle \
  -F sourceMap=@sourcemap.js \
  -F overwrite=true \
  -F /workspace/app/index.ios.js=@app/index.ios.js
