### ISSUE TITLE
Build fails for iOS 2.13: linker command failed with exit code 1

### ISSUE THREAD

**Issue by mayurgrexit** [bugsnag/bugsnag-react-native#328]
### Description

Currently, I am evaluating bugsnag with React Native.

```
npm install bugsnag-react-native@2.13.1 --save
react-native link bugsnag-react-native
pod install
```
### Issue
In Xcode, **both release & debug** builds fails with the error,
```
ld: library not found for -lBugsnagReactNative
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Environment
Library versions:
react-native: 0.56.0
react: 16.4.1
bugsnag-react-native: 2.13.1
cocoapods: 1.6.1
Xcode: Version 10.1 (10B61)

**Not sure why this is happening. Please help me fix the error.**

**Comment by mayurgrexit** [comment]
I just tried the and example app in the folder "plain" from this repo.
This is what I did

```
npm install
cd ios/ && pod init && cd ..
react-native link bugsnag-react-native
cd ios/ && pod install
```

In Xcode, I tried running the build, I get a different error
```
In file included from /Users/mayur/Documents/bugsnag-react-native/examples/plain/node_modules/bugsnag-react-native/cocoa/BugsnagReactNative.m:3:
/Users/mayur/Documents/bugsnag-react-native/examples/plain/node_modules/bugsnag-react-native/cocoa/BugsnagReactNative.h:3:9: fatal error: 'React/RCTBridgeModule.h' file not found
#import <React/RCTBridgeModule.h>
        ^~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

Not sure, why are do these errors keep coming.

**Comment by kattrali** [comment]
Thanks for the report @mayurgrexit. The "plain" example app is already linked, and adding `pod init` would likely break the app. To run the example, follow the instructions [here](https://github.com/bugsnag/bugsnag-react-native/tree/master/examples/plain#setup). The `ios-cocoapods-component` example app ([here](https://github.com/bugsnag/bugsnag-react-native/tree/master/examples/ios-cocoapods-component)) shows how to configure bugsnag-react-native with cocoapods instead of `react-native link` (both should not be used together).
