### ISSUE TITLE
Documentation mismatch with TypeScript Types

### ISSUE THREAD

**Issue by fbartho** [bugsnag/bugsnag-react-native#338]
### Description

I'm trying to make sure that when I submit an Error caught by React's newish `componentDidCatch` API via bugsnag's notify function, that it has the "correct" stack trace.

### Issue

I noticed that the TypeScript type for the `Report` interface declares that the `stacktrace` parameter is a single `string`. https://github.com/bugsnag/bugsnag-react-native/blob/79e84dbf2bdd8789219bea706699739ffc6dfdaa/index.d.ts#L94

The documentation for this attribute, however, declares the type should be an array of stack-frame objects: https://docs.bugsnag.com/platforms/javascript/koa/customizing-error-reports/#stacktrace

### Environment

Library versions:

```shell
yarn list v1.15.2
├─ bugsnag-react-native@2.14.0
└─ react-native@0.59.4
```

- iOS/Android version(s): any
- simulator/emulator or physical device?: any
- debug mode or production?: any

- [x] (iOS only) `[BugsnagReactNative start]` is present in the
  `application:didFinishLaunchingWithOptions:` method in your `AppDelegate`
  class?
- [x] (Android only) `BugsnagReactNative.start(this)` is present in the
  `onCreate` method of your `MainApplication` class?

**Comment by fbartho** [comment]
Additional Question: I'm trying to figure out if I "re-throw" an `Error` from `componentDidCatch` will the original stack trace be preserved?

**Comment by bengourley** [comment]
Hi @fbartho, the types are correct for this library – `report.stacktrace` is a string (it's created [here](https://github.com/bugsnag/bugsnag-react-native/blob/2ae20109b9064fa06ae1acb3c5a4716fea7a8fa7/src/Bugsnag.js#L375)).

The docs you linked to are for our Universal JS notifier, which is currently used on browser js, Node and (since last week) Expo. This library (bugsnag-react-native) is a separate but we do have plans to bring it in line for a consistent experience across all the JavaScript platforms.

Here are the docs for this notifier: https://docs.bugsnag.com/platforms/react-native/react-native/

To answer your other question, an Error in `componentDidCatch()` doesn't typically have a useful stack, as it just has a bunch of frames from the react renderer. If you rethrow it, it should have the same stack. The useful info is in the `info.componentStack` argument though (see the [error boundary intro](https://reactjs.org/blog/2017/07/26/error-handling-in-react-16.html#introducing-error-boundaries) for more info). Hope this helps.
