### ISSUE TITLE
React has been deprecated

### ISSUE THREAD

**Issue by cristianoccazinsp** [bugsnag/bugsnag-react-native#352]
"bugsnag-react-native": "2.18.0",

Please, remove the React dependency from Cocoapods, or provide a work around. Getting "React has been deprecated" after running pod install.

Also, my project uses pods only for some specific libraries, so react is not installed through pods at all, but rather linked directly. Any recommendations?

**Comment by kattrali** [comment]
Hi @cristianoccazinsp, if you want to use CocoaPods instead of `react-native link`, your Podfile will need to reference the React pod inside `node_modules/react-native`. [Here is an example using `bugsnag-react-native`](https://github.com/bugsnag/bugsnag-react-native/tree/master/examples/ios-cocoapods-component#steps-taken-to-configure-a-basic-project) (example Podfile listed in step 4) and here is the [official React Native docs for CocoaPods integration](https://facebook.github.io/react-native/docs/integration-with-existing-apps#configuring-cocoapods-dependencies) (example Podfile about 40% down the page).

There's not much we can do about the version of React published to CocoaPods being deprecated, though the [React Native team seems to be working on this and CocoaPods will be better integrated in the future](https://github.com/facebook/react-native/pull/23563).

**Comment by cristianoccazinsp** [comment]
@kattrali thanks for the response. I have actually followed a different path.

Rather than using pods, I have just manually linked the bugsnag library following https://docs.bugsnag.com/platforms/react-native/react-native/manual-linking-guide/

I think this should be included in the guide, and react-native link should NOT automatically update the pods file since it ends up in that ugly deprecated configuration. Pods should be 100% optional (or even not used at all given the conflict it has with RN)

**Comment by kattrali** [comment]
Thanks for the feedback, @cristianoccazinsp. Integrating using CocoaPods is 100% optional and used in neither of the official `bugsnag-react-native` integrations guides. If `react-native link` is changing your Podfile, that sounds like a bug in the `react-native` package, or something that should be better documented. As far as I know, mixing the two is incompatible.

**Comment by cristianoccazinsp** [comment]
It was most likely related to the fact that I had a podfile already (used to build a library, but without adding any react dependencies). I guess linking just messes up the podfile if there's one available. Anyways, glad I could figure it out.

**Comment by kattrali** [comment]
Ah good to know. I did a bit of digging and came across https://github.com/facebook/react-native/commit/74146cb3158273921b768c97f229695e680ea82d, which might be related since it patches your Podfile.
