### ISSUE TITLE
[Android]  couldn't find "libbugsnag-ndk.so"

### ISSUE THREAD

**Issue by tgensol** [bugsnag/bugsnag-react-native#369]
### Description
I upgraded Bugsnag-react-native to the latest version, and some users are getting crash when they tried to open the app. I am getting an error in bugsnag : 

`java.lang.UnsatisfiedLinkErrorMainApplication.java:146`

What did I miss in the configuration ? I am using RN 0.59 with gradle 5.4.1 and useAndroidX set to true.

Thanking you in advance,
Regards

### Issue

```
java.lang.UnsatisfiedLinkError · dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.appchoose.choose.android-1/base.apk"],nativeLibraryDirectories=[/data/app/com.appchoose.choose.android-1/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libbugsnag-ndk.so"
```

### Environment

- simulator/emulator or physical device?: Physical
- debug mode or production?: production

- [X ] (Android only) `BugsnagReactNative.start(this)` is present in the
  `onCreate` method of your `MainApplication` class?

<details><summary>Error messages:</summary>
ava.lang.UnsatisfiedLinkError · dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.appchoose.choose.android-1/base.apk"],nativeLibraryDirectories=[/data/app/com.appchoose.choose.android-1/lib/arm64, /system/lib64, /vendor/lib64]]] couldn't find "libbugsnag-ndk.so"
</details>

**Comment by kattrali** [comment]
Thanks for the report, @tgensol. What version of Android is on the device?

**Comment by tgensol** [comment]
I have errors with : 
5.0.2 (XT320)
7.1.1 (samsung SM-G930F)
7.1.2 (Pixel)
9 (ONEPLUS A6003)

**Comment by fractalwrench** [comment]
Hi @tgensol - I've tried following the [integration instructions](https://deploy-preview-962--docs-bugsnag.netlify.com/platforms/react-native/react-native) in our `examples/plain` sample app in this project and wasn't able to reproduce this behaviour on a Nexus 4 running API 22. I'm using bugsnag-react-native v2.21.0, v4.4.0 of the bugsnag gradle plugin, and gradle 4.10.2.

I also decompiled the APK using Android Studio's APK analyzer which confirmed that the SO files are in the `lib` directory of the APK. Would you be able to confirm whether you can reproduce this behaviour consistently, or whether your app differs from this setup at all?

If your app uses APK splits or App Bundles that would also be very useful to know, and particularly what architectures you build for if so. This error can sometimes be caused by users side-loading an APK split which is the wrong architecture for their device, so it'd be good to rule that out.

**Comment by tgensol** [comment]
Hi @fractalwrench ,
Thanks for your help ! I also tried myself to reproduce it, but I cannot... It only happens on ~50 users (over thousands of users), 
- I am using gradle 5.4.1
- I am using App Bundles

Maybe my build.gradle file is mis-configured ? 

I am using 

```
  ndk {
            abiFilters  "armeabi-v7a", "x86", "arm64-v8a", "x86-64"
        }
and 

splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86", "arm64-v8a", "x86-64"
        }
    }
```

whereas in your examples you are using : 
```
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }
    }
    splits {
        abi {
            reset()
            enable enableSeparateBuildPerCPUArchitecture
            universalApk false  // If true, also generate a universal APK
            include "armeabi-v7a", "x86"
        }
    }
```
I will put an example of error I got today : 

```
batteryLevel   0.4 
brand   samsung
charging false
cpuAbi  [
  "armeabi-v7a",
  "armeabi"
]
dpi 420
emulator false
freeDisk 11679260672
freeMemory 125098104
manufacturer  samsung
model SM-A510F
networkAccess cellular
orientation portrait
osName android
osVersion 7.0
runtimeVersions {
  "osBuild": "NRD90M.A510FXXU8CSC3",
  "androidApiLevel": "24"
}
```
[Uploading bugsnag_error_stacktrace_java.lang.UnsatisfiedLinkError_event_5d079e9100441e60ec760000.txt…]()

Best regards

**Comment by fractalwrench** [comment]
Hi @tgensol - your build.gradle seems configured correctly. If you're using App Bundles then sometimes this can result in an `UnsatisfiedLinkError` if a user side-loads an APK with the wrong architecture, as no native library will be found by Android. Keepsafe wrote a great post explaining this in more detail [here](https://medium.com/keepsafe-engineering/the-perils-of-loading-native-libraries-on-android-befa49dce2db).

Would you be able to send in a URL of an `UnsatisfiedLinkError` from your bugsnag dashboard to support@bugsnag.com, and a link to this issue for context? I'll then be able to view additional information that's available in the error report, which might reveal whether this is a different issue from APK side-loading.

**Comment by pqkluan** [comment]
Hi @fractalwrench , our app also encountered this issue. Here is the [issue link](https://app.bugsnag.com/eatsy-technologies-1/dinner-prod/errors/5d24ee0b70bfb2001afc7b8e?i=em&m=ds&pivot_tab=event) to our dashboard.

**Comment by mattdyoung** [comment]
Hi @pqkluan 

We've taken a look at your error and the occurrences fall into two cases.

1. Error message: `... couldn't find "libbugsnag-ndk.so"`
We believe this error is due to users side-loading an APK split generated from an App Bundle which is the wrong architecture for their device. Keepsafe wrote a great [blog post](https://medium.com/keepsafe-engineering/the-perils-of-loading-native-libraries-on-android-befa49dce2db) where they found similar behaviour was caused by users downloading the wrong APK from a 3rd party source.

2. Error message: `dlopen failed: couldn't map "/.../split_config.arm64_v8a.apk!/lib/arm64-v8a/libbugsnag-ndk.so" segment 0: Permission denied`
Another customer was able to reproduce this error by installing from an APK built from an App Bundle using Google Play and moving the app to SD card storage. They found the issue went away when they downgraded Android Gradle Plugin to 3.2. We believe this is likely an issue with Android Gradle Plugin as even removing the Bugsnag library, they found the issue persisted with a different native library.

**Comment by pqkluan** [comment]
Hi, @mattdyoung Thanks for the advice, but I don't think the 1st theory is possible since there are more than 150 users affected by this issue, and there shouldn't be not that much people willing to manually install our app outside of PlayStore.

For the 2nd one, downgrading the Android Gradle Plugin is also not a possible solution for us since there are other dependencies require newer gradle version.

**Comment by mattdyoung** [comment]
Hi @pqkluan 

Regarding 1, roughly what percentage of your userbase are the 150 users? Are you seeing this only on particular devices?

For 2, there is very little we can do as this is an issue with Android Gradle Plugin:
https://issuetracker.google.com/issues/127691101

That thread suggested that using `android.bundle.enableUncompressedNativeLibs=false` should work around the issue.

**Comment by ben-j69** [comment]
I encounter the same error on my dev build since Android Studio 3.5 and gradle update...

**Comment by abigail-bugsnag** [comment]
@ben-j69 thanks for your comment. I don't know if you saw @mattdyoung response above?
> Another customer was able to reproduce this error by installing from an APK built from an App Bundle using Google Play and moving the app to SD card storage. They found the issue went away when they downgraded Android Gradle Plugin to 3.2. We believe this is likely an issue with Android Gradle Plugin as even removing the Bugsnag library, they found the issue persisted with a different native library.

**Comment by benoitdion** [comment]
seeing the same issue as @ben-j69 with `2.23.1`, it did not reproduce on `2.22.4`

**Comment by benoitdion** [comment]
With react-native 60, build tools is now at 3.5.0: https://github.com/facebook/react-native/blob/4763000554c71be40b82a740651706781acad2e3/template/android/build.gradle#L15

**Comment by mattdyoung** [comment]
Hi @benoitdion 

Which error are you seeing?

Is it one of the errors referred to in my previous response here?
https://github.com/bugsnag/bugsnag-react-native/issues/369#issuecomment-517284896

Or something different?

Would you be able to write in to support@bugsnag.com with a link to the related error in your Bugsnag dashboard so we can examine the full stacktrace and see if we can identify the cause?

**Comment by khonkaengame** [comment]
I have same issue.

**Comment by mattdyoung** [comment]
@khonkaengame 
Are you seeing one of the 2 errors described in my previous response here?
https://github.com/bugsnag/bugsnag-react-native/issues/369#issuecomment-517284896

Also v4.6.5 of which library?

**Comment by khonkaengame** [comment]
It's Bugsnag.unitypackage library.

**Comment by abigail-bugsnag** [comment]
@khonkaengame are you able to say which of the errors you are seeing?
Are you getting
Error message: `... couldn't find "libbugsnag-ndk.so"`
or
Error message: `dlopen failed: couldn't map "/.../split_config.arm64_v8a.apk!/lib/arm64-v8a/libbugsnag-ndk.so" segment 0: Permission denied`

**Comment by khonkaengame** [comment]
@abigail-bugsnag 
I am getting couldn't find "libbugsnag-ndk.so"

**Comment by mattdyoung** [comment]
Hi @khonkaengame 

We've seen this error caused by users side-loading an APK split generated from an App Bundle which is the wrong architecture for their device.

Are you able to reproduce this error on an app installed from the play store, rather than an APK downloaded from an unofficial source?

**Comment by mattdyoung** [comment]
Hi @khonkaengame @pqkluan @ben-j69 @benoitdion (and anyone else seeing this error).

We've been investigating further and there are a few scenarios where linkage errors can occur which would result in you seeing the error message `... couldn't find "libbugsnag-ndk.so"`:
- User side-loading an APK from an installation source other than Google Play with the wrong architecture
- Android's PackageManager not always copying native libs when installing, further details here: https://medium.com/keepsafe-engineering/the-perils-of-loading-native-libraries-on-android-befa49dce2db
- A now resolved gradle plugin bug that caused some app bundles not to contain the correct native library

These intermittent linkage errors can occur particularly on older versions of Android. Our suggested approach to avoid them would be to preload the SO file with [ReLinker](https://github.com/KeepSafe/ReLinker):
```
ReLinker.loadLibrary(this, "bugsnag-ndk");
Bugsnag.init(this);
```

If you're also using our ANR detection you may see a similar error message `... couldn't find "libbugsnag-plugin-android-anr.so"` for which we'd recommend the same approach:
```
ReLinker.loadLibrary(this, "bugsnag-plugin-android-anr");
Bugsnag.init(this);
```

We did consider including and using ReLinker directly in bugsnag-android but decided against it as this would have had an impact on the size of the library, even for customers unaffected by this issue.

**Comment by khonkaengame** [comment]
Sorry for my ignorance.

How to use ReLinker in unity project?

**Comment by khonkaengame** [comment]
@mattdyoung  Thank you i will try.
