### ISSUE TITLE
Full stacktrace not shown if bundle path is difference from android assets folder

### ISSUE THREAD

**Issue by gajendrakumartwinwal** [bugsnag/bugsnag-react-native#370]
### Environment

Library versions:

```shell

```

- cocoapods version (if any) (`pod -v`):
- iOS/Android version(s):
- simulator/emulator or physical device?:
- debug mode or production?:

- [ ] (iOS only) `[BugsnagReactNative start]` is present in the
  `application:didFinishLaunchingWithOptions:` method in your `AppDelegate`
  class?
- [ ] (Android only) `BugsnagReactNative.start(this)` is present in the
  `onCreate` method of your `MainApplication` class?

### Example Repo

- [ ] Create a minimal repository that can reproduce the issue after running
  `yarn install` and `react-native run-ios`/`react-native run-android`
- [ ] Link to it here:

### Example code snippet

```js
import { Client, Configuration } from 'bugsnag-react-native';

// (Insert code sample to reproduce the problem)
```

<details><summary>Error messages:</summary>

```

```
</details>

**Comment by bengourley** [comment]
Hi @gajendrakumartwinwal, there isn't enough information in this report for us to help you out. Please could you write in to support@bugsnag.com with more information? The following kinds of thing are useful:

- expected behaviour
- actual behaviour (links to errors, or screenshots would be ideal)
- how you are uploading sourcemaps
- how your android paths are different from a typical project

We'll be able to cross-reference with errors in your dashboard and see your uploaded source maps to help debug the problem.

Thanks!

**Comment by bengourley** [comment]
I've just checked in with our support team and see that you've already started a conversation there 💫
