### ISSUE TITLE
RCTGetReactNativeVersion ***XCODE*** fixed!

### ISSUE THREAD

**Issue by bakystefan** [bugsnag/bugsnag-react-native#371]
Into your BugSnagReactNative.m file,
you need to change ### _RCTGetReactNativeVersion_()
In function **_findReactNativeVersion_**

fix: ` NSDictionary *versionMap = RCT_REACT_NATIVE_VERSION;`
old:`  NSDictionary *versionMap = RCTGetReactNativeVersion();`
problem will be fixed. 

this is definition: 
`

#define RCT_REACT_NATIVE_VERSION @{ \
  @"major": @(number), \
  @"minor": @(number), \
  @"patch": @(number), \
  @"prerelease": [NSNull null], \
}
check this link: 
`
https://github.com/facebook/react-native/blob/6df2edeb2a33d529e4b13a5b6767f300d08aeb0a/scripts/bump-oss-version.js

**Comment by bengourley** [comment]
Hi @bakystefan, what version of React Native are you using?

It looks like React Native has had [the `RCTGetReactNativeVersion()` implementation of this feature](https://github.com/facebook/react-native/commit/30469ed00170a74743d2ba5aadce61aae742715c#diff-fd55147d0508f1081aba561f6185d27b) since v0.55.0. We support back to v0.50.0, so this looks like something we should fix.

Thanks!

**Comment by bakystefan** [comment]
Version on my project is 53.0.3. Thanks!

**Comment by bengourley** [comment]
This is now released as of [v2.22.2](https://github.com/bugsnag/bugsnag-react-native/releases/tag/v2.22.2).
