### ISSUE TITLE
Clarification: How can I differentiate and config the dev and production in a single configuration

### ISSUE THREAD

**Issue by nihp** [bugsnag/bugsnag-react-native#427]
How can I set configuration for development and production environment in bugsnag.

(i.e) I am going to test the app in dev and then I need to move for production. What are the changes that needs to be made and how can I automate that.

If I need to build for production means it needs to go for production level and If I need to go to development means it needs to show in Development in a **single config**.

**Comment by mattdyoung** [comment]
Hi @nihp 

We'd recommend configuring the release stage to different values e.g. 'development' / 'production' so that you can easily filter the errors from different environments in Bugsnag:
https://docs.bugsnag.com/platforms/react-native/react-native/configuration-options/#releasestage

You could read that value in from an environment variable or external config file or use different build configurations.
