### ISSUE TITLE
Reporting unhandled errors not working on non-debug env.

### ISSUE THREAD

**Issue by Andreyco** [bugsnag/bugsnag-react-native#47]
**Symptoms:**
Having staging/release (or call it production) environment...
- Bugsnag does not capture unhandled errors
- Bugsnag does sent reports when `notify` is used.

All works as expected in development environment.

**Possible source of this problem** - [default error handler](https://github.com/bugsnag/bugsnag-react-native/blob/master/lib/Bugsnag.js#L45-L47).
What I understand, default error handler just shuts the app down - there is no time for Bugsnag to complete notification request.

**Possible solution (maybe?)**
- pass control to default handler when request is resolved. Control would be passed with _delay_.
- cache and send reports on next start (this would probably require passing control to default handler with _delay_ anyway)

Notes:
- despite I tested Android only, it affects iOS as well.

**Comment by Andreyco** [comment]
Issue found. Without passing control to default error handler, I see error notification in Bugsnag Dashboard.

**Comment by kattrali** [comment]
Thanks for the detailed report, @Andreyco. This is potentially related to https://github.com/bugsnag/bugsnag-android/issues/136, though I think your possible solution is correct, and the uncaught handler should wait for `notify` to complete. The next steps will be to add a callback to `notify` to ensure it is completed and also to move forward on the linked issue, to ensure that case is also handled. This is an android-specific issue since reports are written to disk synchronously when a crash occurs on iOS.

**Comment by Andreyco** [comment]
TY!

**Comment by vikeri** [comment]
Hmm, I still have this issue even though I updated to `1.2.0`. Any ideas?

**Comment by borhub** [comment]
@vikeri The root cause might be https://github.com/bugsnag/bugsnag-android/issues/138 (regression in https://github.com/bugsnag/bugsnag-android/issues/137 ) ?

**Comment by vikeri** [comment]
@borhub Ok, is this fixed in 1.2.2?
